configuration:
  endpoint: http://marcat_st.atcult.it:8085/configurations/entries
  baseUrl: marccat

logging:
  level:
    root: ERROR
    net.sf: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
    ru.yandex: ERROR
    org.folio.marccat: INFO

server:
  port: 8080

configuration:
  cache:
    expire: 120
